# Dockerfile para o Backend (Node/TS)

# Dockerfile para o Backend (Node/TS) - Clona do GitHub
FROM node:20-alpine AS build
WORKDIR /app
# Clona o repositório diretamente
RUN apk add --no-cache git \
	&& git clone --branch main https://github.com/DevRogerMattes/dom2.git .
RUN npm ci
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./
EXPOSE 3001
CMD ["node", "dist/server.js"]
