version: '3.8'

networks:
  DomiusNet:
    external: true

services:
  frontend:
    image: domius-frontend:latest # Gere e envie esta imagem para o Docker Hub ou crie localmente
    networks:
      - DomiusNet
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: domius-backend:latest # Gere e envie esta imagem para o Docker Hub ou crie localmente
    networks:
      - DomiusNet
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://domius:rGr#2291755@postgres:5432/domius_db
      - STRIPE_SECRET_KEY=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
      - STRIPE_PUBLISHABLE_KEY=pk_live_51S9bKtFMpUqhOvgtEW9H4MFHcYGF5mqwRwmX8dfREAHrne4VApk0J5JjCMiyAB1LeXxec9UJvSGFPD8OE5tP0XaL00xle5BC3O
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    networks:
      - DomiusNet
    environment:
      POSTGRES_DB: domius_db
      POSTGRES_USER: domius
      POSTGRES_PASSWORD: rGr#2291755
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
