version: '3.8'

networks:
  DomiusNet:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: domius-frontend
    networks:
      - DomiusNet
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: domius-backend
    networks:
      - DomiusNet
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://usuario:senha@postgres:5432/nome_do_banco
      - STRIPE_SECRET_KEY=
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: domius-postgres
    networks:
      - DomiusNet
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
